# The bluetooth address used by your bed
BED_ADDRESS: "00:00:00:00:00:00"

# MQTT credentials
MQTT_USERNAME: mqtt-user
MQTT_PASSWORD: mqtt-pass
MQTT_SERVER: 127.0.0.1
MQTT_SERVER_PORT: 1883
MQTT_TOPIC: bed

# Bed controller type, supported values are
# "serta", "jiecang", "dewertokin", and "linak"
BED_TYPE: serta

# Optional checkin parameters
MQTT_CHECKIN_TOPIC: checkIn/bed
MQTT_CHECKIN_PAYLOAD: OK
MQTT_ONLINE_PAYLOAD: online
MQTT_QOS: 0